#!/usr/bin/env python3

import os

colors = {
        "white": "#cccccc",
        "yellow": "#ffff00",
        "red": "#ff0000"
        }

def get_color_from_load(load):
    if load <= 4:
        return colors["white"]
    elif 4 < load <=6:
        return colors["yellow"]
    else:
        return colors["red"]

def get_load():
    return os.getloadavg()[0]

def main():
    load = get_load()
    color = get_color_from_load(load)
    print("{0:.2f}".format(load))
    print("{0:.2f}".format(load))
    print(color)

if __name__=="__main__":
    main()
